name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: golang-alpine
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .
